export { default as Account } from './Account';
export { default as Dashboard } from './Dashboard';
export { default as NotFound } from './NotFound';
export { default as Products } from './Products';
export { default as Bank } from './Bank';
export { default as Sale } from './Sale';
export { default as Settings } from './Settings';
export { default as SignIn } from './SignIn';
export { default as SignUp } from './SignUp';
export { default as ResetPass } from './ResetPass';
export { default as VerifyEmail } from './VerifyEmail';
export { default as Category } from './Category'
export { default as UserList } from './UserList';
